### ISSUE TITLE
Xplayer can't load grilo plugin

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/xplayer#22] opened 2016-05-26 12:35 UTC
I compiled xplayer with grilo 0.3 but xplayer can't load it. Follow error is shown

`
Couldn't load the '/usr/lib64/xplayer/plugins/grilo/grilo.ui'. /usr/lib64/xplayer/plugins/grilo/grilo.ui:113:1 Invalid object type 'XplayerSearchEntry'.
Make sure that XPlayer is properly installed.
`

**Comment by anandrkris** [comment] 2016-06-22 15:18
Not sure, but I can see a PR was pulled related to this. 
https://github.com/linuxmint/xplayer/commit/deb5dd0cde027754ee1fe67e2695448ed07a29d5

**Comment by ion201** [comment] 2016-07-09 02:40
I've also noticed this specifically on arch linux with Grilo 0.3.1. I see that grilo on arch has a dependency on totem-plparser, perhaps there is a conflict or incompatibility there vs xplayer? Fwiw, I've resolved this temporarily in the aur by just bumping the required grilo lib version in configure.ac to ensure it doesn't get enabled when compiling.

**Comment by marmistrz** [comment] 2016-09-26 09:22
After rebuilding xplayer under Arch the problem disappeared.

**Comment by JosephMcc** [comment] 2016-09-26 09:42
Is this still an issue?

**Comment by marmistrz** [comment] 2016-09-26 15:59
Hmm... not a problem for me right now... but maybe installing first xplayer, then totem would be a problem. 
Don't have time to test it. 

Alternatively we can close it until someone bumps into it again.

**Comment by JosephMcc** [comment] 2016-09-26 18:55
@marmistrz Thanks for the feedback.

**Comment by vladimir-didenko** [comment] 2016-09-27 15:47
Sorry for delay but issue is still here.

**Comment by vladimir-didenko** [comment] 2016-09-27 15:54
looks like still doesn't work in Arch as well

https://aur.archlinux.org/packages/xplayer/

**Comment by marmistrz** [comment] 2016-09-27 16:04
Ok, indeed, that's the reason why this worked. Apparenlty ion203 simply didn't bump the revision.

> Re: grilo; I completely disabled grilo in the PKGBUILD by bumping the required version in configure.ac from 0.2.0 to 0.9.0 (there's no autoconf option for it). Haven't seen anything new about that, so going to leave that disabled for now.

**Comment by ViniciusBRodrigues** [comment] 2016-11-28 18:58
Confirmed in openSUSE leap 42.2

`xplayer

(xplayer:22243): Gtk-WARNING **: Allocating size to GtkToolButton 0x229b5a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(xplayer:22243): Gtk-WARNING **: Allocating size to GtkToolButton 0x229b770 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(xplayer:22243): Gtk-WARNING **: Allocating size to GtkToolButton 0x229b940 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(xplayer:22243): Gtk-WARNING **: Allocating size to GtkToolButton 0x229bb10 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_scrollable_get_vadjustment: assertion 'GTK_IS_SCROLLABLE (scrollable)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Xplayer-CRITICAL **: xplayer_sidebar_add_page: assertion 'GTK_IS_WIDGET (main_widget)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_scrolled_window_get_vadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_scrolled_window_get_vadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): Xplayer-CRITICAL **: xplayer_sidebar_add_page: assertion 'GTK_IS_WIDGET (main_widget)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(xplayer:22243): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xplayer:22243): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xplayer:22243): Gtk-CRITICAL **: gtk_action_get_name: assertion 'GTK_IS_ACTION (action)' failed
Falha de segmentação (imagem do núcleo gravada)
`

**Comment by jristz** [comment] 2017-04-28 15:26
So it can be reduced to
Xplayer need grillo which need totem-plparser (so something) with no --without-grillo in xplayer to prevent this
Totem-plparser and xplayer-parser can coexiat but most programs will only look or build against the totem version.
Grillo will work with totem-plparser but xvideo will spect xvidep-plparser instead
Maybe fork grillo into something so xvideo can link against this fork and this against xvideo-plparser without problems?

**Comment by XRevan86** [comment] 2018-09-13 14:06
#119 should take care of that.
And no, it has nothing to do with plparser ;-).

**Closed** 2018-10-01 15:10 UTC
