### ISSUE TITLE
Large control icons in full screen

### ISSUE THREAD

**Issue by cossio** [linuxmint/xplayer#55] opened 2016-12-02 15:56 UTC
This seems to be a bug.

Open a video with Xplayer. Then use the arrow keys to navigate, either go forward or backward. Switch to full screen, and keep navigating with the keys. Eventually, huge white control icons indicating forward or backward navigation appear on the screen, hiding a big chunk of the video. 

Either remove the control icons, or make them smaller.

**Comment by clefebvre** [comment] 2016-12-08 12:43
I can't reproduce this issue.

**Comment by clefebvre** [comment] 2016-12-08 12:45
duplicate of https://github.com/linuxmint/xplayer/issues/53

**Closed by clefebvre** 2016-12-08 12:45 UTC
Labels: BUG
